<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tuw_shmfw</name>
  <version>0.1.0</version>
  <description>Shared memory framework for interprocess communication</description>
  <maintainer email="markus.bader@tuwien.ac.at">Markus Bader</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>libboost-date-time-dev</depend>
  <depend>libboost-thread-dev</depend>
  <depend>libboost-program-options-dev</depend>
  <depend>libncurses-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
